// license-header java merge-point
// Generated by andromda-jsf cartridge (controllers\ControllerImpl.java.vsl)
package org.andromda.timetracker.web.timetrackerhome;

/**
 * @see org.andromda.timetracker.web.timetrackerhome.HomeController
 */
public class HomeControllerImpl extends HomeController
{
    /**
     * The serial version UID of this class. Needed for serialization.
     */
    private static final long serialVersionUID = -1295450003436329552L;

}
