// license-header java merge-point
//
// Generated by SessionBeanImpl.vsl in andromda-ejb3-cartridge on 03/29/2012 12:08:34.
//
package org.andromda.timetracker.service;

import org.andromda.timetracker.vo.UserDetailsVO;

/**
 * @see SecurityServiceBase
 * Remember to manually configure the local business interface this bean implements if originally you only
 * defined the remote business interface. However, this change is automatically reflected in the ejb-jar.xml.
 * Do not specify the javax.ejb.Stateless annotation
 * Instead, the session bean is defined in the ejb-jar.xml descriptor.
 */
// Uncomment to enable webservices for SecurityServiceBean
// @javax.jws.WebService(endpointInterface = "org.andromda.timetracker.service.SecurityServiceWSInterface", serviceName = "SecurityService")
/*
 * @Stateless
 * @Scope(ScopeType.CONVERSATION)
 * @Name("securityService")
 * @Interceptors(SeamInterceptor.class)
 * @JndiName("java:app/core/SecurityServiceBean")
 */
public class SecurityServiceBean extends SecurityServiceBase implements SecurityServiceRemote
{

    // --------------- Constructors ---------------

    /**
     * Default constructor extending base class default constructor
     */
    public SecurityServiceBean()
    {
        super();
    }

    // -------- Business Methods Impl --------------

    /**
     * @see SecurityServiceBase#getUserDetails(String)
     */
    @Override
    protected UserDetailsVO handleGetUserDetails(final String username) throws Exception
    {
        // TODO: put your implementation here.
        // Dummy return value, just that the file compiles
        return null;
    }

    // -------- Lifecycle Callback Implementation --------------

}
