// license-header java merge-point
//
// Generated by test/SessionTest.vsl in andromda-ejb3-cartridge on 03/29/2012 12:08:36.
//
package org.andromda.timetracker.service.test;

import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;
import org.testng.annotations.Test;

/**
 * Service test class SecurityServiceTest for testing with TestNG
 * Check the testng.xml for initialization of the EJB3Container before running any tests.
 */
public class SecurityServiceTest
{
    private static final Log logger = LogFactory.getLog(SecurityServiceTest.class);

    @Test
    public void testGetUserDetails()
    {
        // try
        // {
        // org.andromda.timetracker.service.SecurityServiceRemote securityService = (org.andromda.timetracker.service.SecurityServiceRemote)EJB3Container.getInitialContext().lookup("SecurityServiceBean/remote");
        // test implementation
        // }
        // catch (Exception ex)
        // {
        // logger.warn("Failed test testGetUserDetails()", ex);
        // }
    }

}
