
    create table TASK (
        ID BIGINT generated by default as identity,
        NAME VARCHAR(256) not null unique,
        primary key (ID)
    );

    create table TIMECARD (
        ID BIGINT generated by default as identity,
        COMMENTS VARCHAR(256) not null,
        START_DATE DATETIME not null,
        STATUS VARCHAR(256) not null,
        APPROVER BIGINT,
        SUBMITTER BIGINT not null,
        primary key (ID)
    );

    create table TIME_ALLOCATION (
        ID BIGINT generated by default as identity,
        TIME_PERIOD_START_TIME DATETIME not null,
        TIME_PERIOD_END_TIME DATETIME not null,
        TASK BIGINT not null,
        TIMECARD BIGINT not null,
        primary key (ID)
    );

    create table USERS (
        ID BIGINT generated by default as identity,
        USERNAME VARCHAR(50) not null unique,
        PASSWORD VARCHAR(256) not null,
        FIRST_NAME VARCHAR(256) not null,
        LAST_NAME VARCHAR(256) not null,
        EMAIL VARCHAR(50) not null unique,
        IS_ACTIVE BIT not null,
        CREATION_DATE DATETIME not null,
        COMMENT VARCHAR(256),
        primary key (ID)
    );

    create table USER_ROLE (
        ID BIGINT generated by default as identity,
        ROLE VARCHAR(256) not null,
        USERS BIGINT,
        primary key (ID)
    );

    alter table TIMECARD 
        add constraint TIMECARD_SUBMITTERC 
        foreign key (SUBMITTER) 
        references USERS;

    alter table TIMECARD 
        add constraint TIMECARD_APPROVERC 
        foreign key (APPROVER) 
        references USERS;

    alter table TIME_ALLOCATION 
        add constraint TIME_ALLOCATION_TASKC 
        foreign key (TASK) 
        references TASK;

    alter table TIME_ALLOCATION 
        add constraint TIME_ALLOCATION_TIMECARDC 
        foreign key (TIMECARD) 
        references TIMECARD;

    create index USERNAME_INDEX on USERS (USERNAME);

    alter table USER_ROLE 
        add constraint USER_ROLE_USERSC 
        foreign key (USERS) 
        references USERS;
