// license-header java merge-point
// Generated by andromda-jsf cartridge (controllers\crud\ControllerImpl.java.vsl)
package org.andromda.timetracker.domain.crud;

import java.io.Serializable;

/**
 * @see org.andromda.timetracker.domain.crud.MovieController
 */
public class MovieControllerImpl extends MovieController implements Serializable
{
    /**
     * The serial version UID of this class. Needed for serialization.
     */
    private static final long serialVersionUID = 6939118457502766958L;
}
