// license-header java merge-point
// Generated by andromda-jsf cartridge (controllers\crud\ControllerImpl.java.vsl)
package org.andromda.timetracker.domain.crud;

import java.io.Serializable;

/**
 * @see org.andromda.timetracker.domain.crud.UserRoleController
 */
public class UserRoleControllerImpl extends UserRoleController implements Serializable
{
    /**
     * The serial version UID of this class. Needed for serialization.
     */
    private static final long serialVersionUID = -802576977142728635L;
}
