// license-header java merge-point
// Generated by andromda-jsf cartridge (controllers\crud\ControllerImpl.java.vsl) on 03/26/2012 10:17:22+0200
package org.andromda.timetracker.domain.crud;

import java.io.Serializable;

/**
 * @see org.andromda.timetracker.domain.crud.UserController
 */
public class UserControllerImpl extends UserController implements Serializable
{
    /**
     * The serial version UID of this class. Needed for serialization.
     */
    private static final long serialVersionUID = -6474920914620504316L;
}
