/* Generated by AndroMDA, do not edit! */
/* Run this script as the schema owner to drop all schema objects */

SET echo ON;

WHENEVER SQLERROR CONTINUE;
WHENEVER OSERROR  EXIT;

/* drop all tables */
drop table USERS cascade constraints ;
drop table TASK cascade constraints ;
drop table TIME_ALLOCATION cascade constraints ;
drop table TIMECARD cascade constraints ;
drop table USER_ROLE cascade constraints ;

@drop-sequences.sql

exit;