/* Generated by AndroMDA, do not edit! */
/* Run this script as the schema owner to drop all sequences */

drop sequence USERS_SEQ ;
drop sequence TASK_SEQ ;
drop sequence TIME_ALLOCATION_SEQ ;
drop sequence TIMECARD_SEQ ;
drop sequence USER_ROLE_SEQ ;
drop sequence MOVIE_SEQ ;

exit;
