// license-header java merge-point
/**
 * This is only generated once! It will never be overwritten.
 * Generated by DaoImpl.vsl in andromda-ejb3-cartridge on 03/29/2012 12:08:35.
 * You can (and have to!) safely modify it by hand.
 */
package org.andromda.timetracker.domain;

import org.andromda.timetracker.vo.TimeAllocationVO;

/**
 * @see TimeAllocation
 */
// @Stateless
// @Stateful if stateful uncomment the destroy method
// @Name("timeAllocationDao")
// @Scope(ScopeType.EVENT)
// @AutoCreate
// @JndiName("java:app/core/TimeAllocationDaoImpl")
public class TimeAllocationDaoImpl extends TimeAllocationDaoBase
{
    /**
     * @see org.andromda.timetracker.domain.TimeAllocationDao#toTimeAllocationVO(TimeAllocation, TimeAllocationVO)
     */
    @Override
    public void toTimeAllocationVO(final TimeAllocation sourceEntity, final TimeAllocationVO targetVO)
    {
        // TODO verify behavior of toTimeAllocationVO
        super.toTimeAllocationVO(sourceEntity, targetVO);
    }

    /**
     * @see org.andromda.timetracker.domain.TimeAllocationDao#toTimeAllocationVO(TimeAllocation)
     */
    @Override
    public TimeAllocationVO toTimeAllocationVO(final TimeAllocation entity)
    {
        // TODO verify behavior of toTimeAllocationVO
        return super.toTimeAllocationVO(entity);
    }

    /**
     * Retrieves the entity object that is associated with the specified value object
     * from the object store. If no such entity object exists in the object store,
     * a new, blank entity is created
     */
    private TimeAllocation loadTimeAllocationFromTimeAllocationVO(final TimeAllocationVO timeAllocationVO)
    {
        // TODO implement loadTimeAllocationFromTimeAllocationVO
        throw new UnsupportedOperationException("org.andromda.timetracker.domain.loadTimeAllocationFromTimeAllocationVO(TimeAllocationVO) not yet implemented.");

        /*
         * A typical implementation looks like this:
         * TimeAllocation timeAllocation = this.load(timeAllocationVO.getId());
         * if (timeAllocation == null)
         * {
         * timeAllocation = TimeAllocation.Factory.newInstance();
         * }
         * return timeAllocation;
         */
    }

    /**
     * @see org.andromda.timetracker.domain.TimeAllocationDao#timeAllocationVOToEntity(TimeAllocationVO)
     */
    @Override
    public TimeAllocation timeAllocationVOToEntity(final TimeAllocationVO timeAllocationVO)
    {
        // TODO verify behavior of timeAllocationVOToEntity
        final TimeAllocation entity = this.loadTimeAllocationFromTimeAllocationVO(timeAllocationVO);
        this.timeAllocationVOToEntity(timeAllocationVO, entity, true);
        return entity;
    }

    /**
     * @see org.andromda.timetracker.domain.TimeAllocationDao#timeAllocationVOToEntity(TimeAllocationVO, TimeAllocation)
     */
    @Override
    public void timeAllocationVOToEntity(final TimeAllocationVO sourceVO, final TimeAllocation targetEntity, final boolean copyIfNull)
    {
        // TODO verify behavior of timeAllocationVOToEntity
        super.timeAllocationVOToEntity(sourceVO, targetEntity, copyIfNull);
    }

}
