// license-header java merge-point
/**
 * This is only generated once! It will never be overwritten.
 // Generated by EmbeddedValueImpl.vsl in andromda-ejb3-cartridge on 03/29/2012 12:08:36.
 * You can (and have to!) safely modify it by hand.
 */
package org.andromda.timetracker.domain;

import java.io.Serializable;

/**
 * @see TimePeriod
 */
public class TimePeriodImpl extends TimePeriod implements Serializable
{
    /**
     * The serial version UID of this class. Needed for serialization.
     */
    private static final long serialVersionUID = -708617510741626676L;

}
