// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by SessionRemote.vsl in andromda-ejb3-cartridge on 04/04/2012 15:12:35.
//
package org.andromda.timetracker.service;

import javax.ejb.Remote;

import org.andromda.timetracker.vo.UserDetailsVO;
import org.andromda.timetracker.vo.UserVO;

/**
 * Remote component interface for the UserServiceBean session bean.
 * The service that implement this business interface is a Seam component. The cartridge
 * will not expose this interface as a Remote business interface for the bean
 * component. Seam components will only have a Local business interface.
 */
@Remote
public interface UserServiceRemote extends UserService
{

    // ------------ Business Methods -----------------

    /**
     *
     */
    public UserVO[] getAllUsers() throws UserDoesNotExistException;

    /**
     *
     */
    public UserVO getUser(String username) throws UserDoesNotExistException;

    /**
     *
     */
    public UserDetailsVO registerUser(UserDetailsVO userDetailVO) throws UserDoesNotExistException;

    /**
     *
     */
    public void removeUser(UserVO userVO) throws UserDoesNotExistException;

}
