// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by SessionInterface.vsl in andromda-ejb3-cartridge on 04/04/2012 15:12:34.
//
package org.andromda.timetracker.service;

/**
 * Parent interface for the UserServiceBean session bean which is
 * extended by Local and Remote business interfaces. Contains constant
 * and attribute accessor method definitions.
 */
public interface UserService
{

    // ----------- Accessors For Constants ------------

    // ------------ Lifecycle Methods -----------------

    public void destroy();
}
