// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by SessionLocal.vsl in andromda-ejb3-cartridge on 04/04/2012 15:12:35.
//
package org.andromda.timetracker.service;

import javax.ejb.Local;

import org.andromda.timetracker.vo.UserDetailsVO;
import org.andromda.timetracker.vo.UserVO;

/**
 * Local component interface for the UserServiceBean session bean.
 * The service that implement this business interface is a Seam component. The cartridge
 * only exposes this interface as a Local business interface for the Seam bean
 * component.
 */
@Local
public interface UserServiceLocal extends UserService
{

    // ------------ Business Methods -----------------

    /**
     *
     */
    public UserVO[] getAllUsers() throws UserDoesNotExistException;

    /**
     *
     */
    public UserVO getUser(String username) throws UserDoesNotExistException;

    /**
     *
     */
    public UserDetailsVO registerUser(UserDetailsVO userDetailVO) throws UserDoesNotExistException;

    /**
     *
     */
    public void removeUser(UserVO userVO) throws UserDoesNotExistException;

    @Override
    public void destroy();

}
