// license-header java merge-point
// Generated by andromda-jsf cartridge (controllers\ControllerImpl.java.vsl)
package org.andromda.timetracker.web.timecarddetails;

/**
 * @see org.andromda.timetracker.web.timecarddetails.TimecardController
 */
public class TimecardControllerImpl extends TimecardController
{
    /**
     * The serial version UID of this class. Needed for serialization.
     */
    private static final long serialVersionUID = 156949676989040542L;

}
